# SPDX-FileCopyrightText: 2019-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet -r requirements.txt
    - name: Checks
      run: |
          pre-commit run --all
