# SPDX-FileCopyrightText: 2019-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

on: [push, pull_request]

env:
  SPACK_REPO: rscohn2/spack
  SPACK_BRANCH: dev/oneapi-standalones

jobs:
  checks:
    if: false
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet -r requirements.txt
    - name: Checks
      run: |
        pre-commit run --all

  gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet -r requirements.txt
    - name: Install spack
      uses: actions/checkout@v2
      with:
        repository: ${{ env.SPACK_REPO }}
        path: spack
        ref: ${{ env.SPACK_BRANCH }}
    - name: Package tests
      run: |
        source spack/share/spack/setup-env.sh
        spack repo add ./repo
        pytest -s tests/test_packages.py::test_gcc
        pytest -s tests/test_packages.py::test_virtual
    - name: Load test
      run: |
        source spack/share/spack/setup-env.sh
        spack load intel-oneapi-tbb
        spack load intel-oneapi-mpi
        spack load intel-oneapi-mkl
        spack load intel-oneapi-dal
        make -C samples cpp-sample.out fortran-sample.out mkl-sample.out mpi-sample.out tbb-sample.out dal-sample.out
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: gcc-logs
        path: |
          /tmp/runner/spack-stage/
          /tmp/runner/intel-oneapi-installer/
          !/tmp/runner/**/*.sh

  intel-compiler:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [icc, icx]
        part: [1, 2]
        os: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet -r requirements.txt
    - name: Install spack
      uses: actions/checkout@v2
      with:
        repository: ${{ env.SPACK_REPO }}
        path: spack
        ref: ${{ env.SPACK_BRANCH }}
    - name: Package tests
      run: |
        source spack/share/spack/setup-env.sh
        spack repo add ./repo
        # spack install intel-oneapi-compilers
        # spack compiler add `spack location -i intel-oneapi-compilers`/compiler/latest/linux/bin/intel64
        # spack compiler add `spack location -i intel-oneapi-compilers`/compiler/latest/linux/bin
        pytest -s tests/test_packages.py::test_${{ matrix.compiler }}_${{ matrix.part }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.compiler }}-${{ matrix.part }}-${{ matrix.os }}-logs
        path: |
          /tmp/runner/spack-stage/
          /tmp/runner/intel-oneapi-installer/
          !/tmp/runner/**/*.sh
