# SPDX-FileCopyrightText: 2019-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet -r requirements.txt
    - name: Install spack
      uses: actions/checkout@v2
      with:
        repository: rscohn2/spack
        ref: dev/sycl-required-libs
        path: spack
    - name: Style and package tests
      run: |
          source spack/share/spack/setup-env.sh
          spack repo add ./repo
          spack install oneapi-test-basic sycl=False
          # pre-commit run --all
